<%@ Page Title="" Language="C#" MasterPageFile="~/Weixinclient/App_Master/all_master.Master" AutoEventWireup="true" CodeFile="SellerSummary.aspx.cs" Inherits="Weixin.SellerSummary" %>
<%@ Register Src="~/Weixinclient/ascx/pagecutphone.ascx" TagName="pageweixincut" TagPrefix="uc1" %>
<%@ Register Src="~/Weixinclient/ascx/querycontrolsm.ascx" TagName="querycontrolsm" TagPrefix="uc2" %>
<%@ Import Namespace="System.Data"  %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
<section >
      <uc2:querycontrolsm ID="querycontrolSM" runat="server" />
    <script type="text/javascript" src="js/sorttable.js"></script>
    <script type="text/javascript" src="js/splittable.js"></script>
    <link href="css/sorttable.css" type="text/css" rel="stylesheet" />
    <style>
		html, body {
			font-family: Arial;
			
			margin: 0;
			padding: 0;
			
		}

        .dwrapper {
         margin-top:40px;
height:380px;
overflow:hidden;
font-size: 10px;
        }
		.dwrapper tr th{
	
}
.grade-w-roll {
    top: 86px;
z-index:1006;
}
	</style>
    <script type="text/javascript">
        $(function () {




            $('#contenttable').fxdHdrCol({
                fixedCols: 2,
                width: "100%",
                height: 380,
                colModal: [{ width: 30, align: 'center' },
                { width: 80, align: 'center' },
                { width: 80, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' },
                { width: 50, align: 'center' }
                ],
                sort: true
            });


            //$('#contenttable tr').each(function (i) {                   // 遍历 tr
            //    $(this).children('td').each(function (j) {  // 遍历 tr 的各个 td
            //        if (j == 1 || j == 2) {
            //            $(this).css("width", 120)
            //        }
            //        else
            //        {
            //            $(this).css("width", 45)
            //        }

            //    });
            //});



        })
    </script>
     
   <div class="dwrapper">
       <table id="contenttable" style="border: solid 1px" >
           <thead>
           <tr >
              <%for (int i = 0; i < dtSource.Columns.Count; i++){ %>
             
              <th style="word-break:break-all; word-wrap:break-word;"><%=dtSource.Columns[i].ColumnName %></th>
             
              <%} %>
             </tr>
               </thead>
           <tbody>
         <%foreach (DataRow item in dtSource.Rows)
             { %>
          <tr>
              <%for (int i = 0; i < dtSource.Columns.Count; i++){ %>
              
   
               <td ><%=item[i] %></td>
              
              
              <%} %>
          </tr>
          <%} %>
               </tbody>
        </table>
   </div>
      

    <!--earch-list end-->
   
  </section>
  <!--section   end-->
</asp:Content>